name: bluesky_2021_1
channels:
  - defaults
  - conda-forge
  - aps-anl-tag
  - nsls2forge
  - pydm-tag
  - pcds-tag
dependencies:
  - python>=3.8
  # remove anaconda package, it makes install and update take much longer or become unsuccessful
  # - anaconda
  - aps-dm-api
  - apstools
  - area-detector-handlers
  - black
  - bluesky>=1.6.2
  - caproto
  - conda-build
  - coverage
  - databroker>=1.0.6
  - databroker-pack
  # - epics-pydb
  - flake8
  - h5py
  - happi
  - hklpy
  - imagecodecs-lite
  - ipython
  - jupyter
  - jupyterlab
  - lxml
  - nexpy
  - notebook
  - ophyd>=1.5.1
  - pandas
  - pandoc
  - pint
  - pip
  - psutil
  - punx
  - pvview
  - pydm
  - pyEpics>=3.4.2
  - pylint
  - pymca
  - pymongo
  - pyqt=5
  - pyRestTable
  - pytest
  - qt=5
  - scikit-image
  - spec2nexus
  - sphinx
  - sphinxcontrib-napoleon
  - stdlogpj
  - twine
  - typhos
  - versioneer
  - xlrd
  - pip:
    - bluesky-live
    # - ipython-genutils==0.2.0
    - sphinx-rtd-theme
    - super-state-machine
