name: bluesky_2024_3

# download:
#   wget https://raw.githubusercontent.com/BCDA-APS/bluesky_training/main/bluesky/environments/environment_2024_3.yml
# create:
#   conda env create -y -n bluesky_2024_3 -f ./environment_2024_3.yml --solver=libmamba
# activate:
#   conda activate bluesky_2024_3

# Add/revise environment variable for default bluesky environment.
# Add to ~/.bash_aliases (or if that does not exist, ~/.bashrc).
# export BLUESKY_CONDA_ENV=bluesky_2024_3

# For more advice about bash environment variables, see:
# https://github.com/BCDA-APS/bluesky_training/blob/main/bluesky/environments/admin/bluesky.md#bash-environment-variables

channels:
  # - apsu  # Must be first for compatible epics-base, pyepics, pvapy
  - conda-forge

  # due to licensing Terms & Conditions,  don't use the defaults channel.
  - nodefaults
  # Note this advice: https://stackoverflow.com/questions/67695893/

dependencies:
  # Use conda to install only the basics and whatever pip can't install.
  # This includes binaries such as Qt and hkl.
  # Everything else by pip.

  # Some Bluesky packages are not ready for 3.12+.
  # Since this uses pip to install most packages, their
  # requirements will not be handled until after the
  # conda environment is installed.
  - python <3.12
  - pip
  - apsu::pvapy
  - apsu::aps-dm-api >=8   # linux-64  osx-64 -- ONLY at APS!
  - hkl   # linux-64
  - nbconvert-pandoc
  - pandoc >3
  - pyqt =5
  - qt =5

  - pip:

    # APS-only
    # - apsbss  # only works on APS subnet

    # user-requested visualization packages
    - c2dataviewer  # EPICS PVA images
    - gemviz  # from tiled
    - mdaviz  # MDA data files
    - nexpy  # HDF5 and SPEC data files
    - pymca  # HDF5 and SPEC data files

    # --- user-requested packages
    - https://github.com/BCDA-APS/adl2pydm/archive/main.zip
    - ophyd-registry
    - punx
    # - pvmail
    - pvview
    - pyRestTable
    - spec2nexus
    - xrayutilities

    # --- Python core packages
    - ipython
    - jupyter
    - jupyterlab
    - notebook
    - numpy <1.999  # avoid any and all numpy 2.0 releases (includes 2.0.0aNNN)
    - psutil

    # --- general support packages
    - apischema
    - bitshuffle
    - h5py
    - hdf5plugin
    # - httpie
    - imagecodecs-lite
    - ipympl
    - lxml
    - pandas
    - pint
    - pymongo
    # - pysumreg
    - scikit-image
    - xlrd

    # --- Bluesky framework packages
    - apstools
    - area-detector-handlers
    - bluesky >=1.12
    - bluesky-httpserver
    - bluesky-kafka
    - bluesky-live
    - bluesky-queueserver
    - bluesky-queueserver-api
    - bluesky-widgets
    - databroker <=1.999
    - databroker-pack
    - happi
    - hklpy >=1.1.1
    - httpx >=0.14  # issue #75
    - ophyd >=1.9
    - pydm
    - tiled[all]
    # https://github.com/pydata/xarray/issues/6818
    - xarray !=2022.6.0  # incompatible with numpy=1.20

    # --- testing and quality assurance
    - black
    - flake8
    - pylint
    - pytest
    - pytest-notebook
    - ruff

    # --- packaging and publishing
    - coverage
    - myst-parser
    - nbsphinx
    - pydata-sphinx-theme
    - pygithub
    - sphinx
    - sphinx-design
    - sphinx-tabs
    - sphinxcontrib-napoleon
    - twine
