name: bluesky_2025_1

# download:
#   wget https://raw.githubusercontent.com/BCDA-APS/bluesky_training/main/bluesky/environments/environment_2024_3.yml
# create:
#   conda env create -y -n bluesky_2025_1 -f ./environment_2025_1.yml
# activate:
#   conda activate bluesky_2025_1

# Add/revise environment variable for default bluesky environment.
# Add to ~/.bash_aliases (or if that does not exist, ~/.bashrc).
# export BLUESKY_CONDA_ENV=bluesky_2025_1

# For more advice about bash environment variables, see:
# https://github.com/BCDA-APS/bluesky_training/blob/main/bluesky/environments/admin/bluesky.md#bash-environment-variables

channels:
  # - apsu  # Must be first for compatible epics-base, pyepics, pvapy
  - conda-forge

  # due to licensing Terms & Conditions,  don't use the defaults channel.
  - nodefaults
  # Note this advice: https://stackoverflow.com/questions/67695893/

  - aps-anl-tag

# Prefer conda install if possible, pip install as fallback.
# https://github.com/BCDA-APS/bluesky_training/pull/334#issuecomment-2613340849
# Some Bluesky packages are not ready for 3.12+.
# Pip installs cannot adjust the Python version but conda can.

dependencies:

  # Since this uses pip to install most packages, their
  # requirements will not be handled until after the
  # conda environment is installed.
  - python
  - apsu::aps-dm-api >=8   # linux-64  osx-64 -- ONLY at APS!
  - apsu::pvapy
  - conda-forge::epics-base
  - hkl   # linux-64
  - nbconvert-pandoc
  - pandoc >3
  - pip
  - pyepics
  - pyqt =5
  - qt =5

  # user-requested visualization packages
  - gemviz  # tiled data server
  - nexpy  # HDF5 and SPEC data files
  - pymca  # HDF5 and SPEC data files

  # --- user-requested packages
  - punx
  - pvmail
  - pvview
  - pyRestTable
  - spec2nexus
  - xrayutilities

  # --- Python core packages
  - ipython
  - jupyter
  - jupyterlab
  - notebook
  - numpy <1.999  # avoid any and all numpy 2.0 releases (includes 2.0.0aNNN)
  - psutil

  # --- general support packages
  - apischema
  - bitshuffle
  - h5py
  - hdf5plugin
  - imagecodecs-lite
  - ipympl
  - lxml
  - pandas
  - pint
  - pymongo
  - scikit-image
  - xlrd

  # --- Bluesky framework packages
  - apstools
  - area-detector-handlers
  - bluesky >=1.12
  - bluesky-httpserver
  - bluesky-kafka
  - bluesky-live
  - bluesky-queueserver
  - bluesky-queueserver-api
  - bluesky-widgets
  - databroker <=1.999
  - databroker-pack
  - happi
  - hklpy >=1.1.1
  - httpx >=0.14  # issue #75
  - ophyd >=1.9
  - pydm
  - tiled[all]
  # https://github.com/pydata/xarray/issues/6818
  - xarray !=2022.6.0  # incompatible with numpy=1.20

  # --- testing and quality assurance
  - black
  - flake8
  - isort
  - mypy
  - pre-commit
  - pylint
  - pytest
  - pytest-notebook
  - ruff

  # --- packaging and publishing
  - babel
  - conda-build
  - coverage
  - ipykernel
  - jinja2
  - markupsafe
  - myst-parser
  - nbsphinx
  - pydata-sphinx-theme
  - pygments
  - pygithub
  - sphinx
  - sphinx-design
  - sphinx-tabs
  - sphinxcontrib-napoleon
  - twine

  - pip:

    # - apsbss  # only works on APS subnet

    - c2dataviewer  # EPICS PVA images
    - guarneri
    - https://github.com/BCDA-APS/adl2pydm/archive/main.zip
    - mdaviz  # MDA data files
    - ophyd-registry
    - pygments-ipython-console
