name: training_2022

# use:
#   date; conda env create --force -f ./environment.yml; date

channels:
  - defaults
  - conda-forge
  - nsls2forge
  - aps-anl-tag

dependencies:

  # --- Python core packages
  - python=3.9
  - ipython
  - jupyter
  - jupyterlab
  - notebook
  - pip
  - psutil

  # --- testing and quality assurance
  - black
  - flake8
  - pylint
  - pytest

  # --- Qt
  - pyqt=5
  - qt=5

  # --- support packages
  - bitshuffle
  - epics-base>=7.0.5
  - h5py
  - hdf5plugin
  - imagecodecs-lite
  - ipympl
  - lxml
  - pandas
  - pint
  - pyEpics>=3.5.0
  - pymongo
  - scikit-image
  - xlrd

  # --- Bluesky framework packages
  # - apstools  moved to pip install
  - area-detector-handlers
  - bluesky>=1.8.1
  - bluesky-queueserver
  - bluesky-queueserver-api
  - bluesky-widgets
  - databroker=1
  - databroker-pack
  - hklpy
  - ophyd>=1.6.3
  - pydm

  # --- user-requested packages
  - nexpy
  - punx
  - pvview
  - pymca
  - pyRestTable
  - spec2nexus
  - stdlogpj
  - xrayutilities

  # --- packaging and publishing
  # - conda-build
  # - coverage
  # - sphinx
  # - sphinxcontrib-napoleon
  # - twine
  # - versioneer

  - pip:
    - apstools
    - https://github.com/BCDA-APS/adl2pydm/archive/main.zip
    # --- optional Bluesky framework packages for evaluation
    # - bluesky-webclient is NOT Python software, don't install it this way
    #    https://github.com/bluesky/bluesky-webclient
