name: training_2022

# use:
#   date -Is; mamba env create --force -f ./environment.yml; date -Is

# then (manually):
# pip install --pre \
#   databroker \
#   tiled[all] \
#   area_detector_handlers


channels:
  - defaults
  - conda-forge
  - nsls2forge
  - aps-anl-tag

dependencies:

  # --- Python core packages
  - python
  - ipython
  - jupyter
  - jupyterlab
  - notebook
  - pip
  - psutil

  # --- testing and quality assurance
  - black
  - coverage
  - coveralls
  - flake8
  - pylint
  - pytest

  # --- Qt
  - pyqt=5
  - qt=5

  # --- general support packages
  - aps-dm-api>=5
  - bitshuffle
  - blosc
  - epics-base>=7.0.5
  - h5netcdf
  - h5py
  - hdf5plugin
  - imagecodecs-lite
  - ipympl
  - lxml
  - pandas
  - pint
  - pyEpics>=3.5.0
  - pymongo
  - scikit-image
  - xlrd

  # --- Bluesky framework packages
  - apstools
  - area-detector-handlers
  - bluesky-queueserver
  - bluesky-queueserver-api
  - bluesky-widgets
  - bluesky>=1.8.1
  - databroker-pack
  - databroker=1
  - hklpy
  - ophyd>=1.6.3
  - pydm

  # --- user-requested packages
  - nexpy
  - punx
  - pvview
  - pymca
  - pyRestTable
  - spec2nexus
  - stdlogpj
  - xrayutilities

  # # --- packaging and publishing
  # - conda-build
  # - sphinx
  # - sphinxcontrib-napoleon
  # - twine
  # - versioneer

  # for tiled install (separately, by pip, as above)
  - anyio
  - dask
  - fastapi
  - httpx
  - jinja2
  - lz4
  - prometheus_client
  - pydantic
  - tifffile
  - uvicorn

  - pip:

    - https://github.com/BCDA-APS/adl2pydm/archive/main.zip
    # --- optional Bluesky framework packages for evaluation
    # - bluesky-webclient is NOT Python software, don't install it this way
    #    https://github.com/bluesky/bluesky-webclient
