# configuration.yml

# configuration for the instrument package
# simple key:value pairs

ADSIM_IOC_PREFIX: "ad:"
GP_IOC_PREFIX: "gp:"

DATABROKER_CATALOG: training

# default RunEngine metadata
beamline_id: Bluesky_training
instrument_name: Bluesky Case Studies
proposal_id: none

# default timeouts (seconds)
PV_TIMEOUT: 60
PV_WRITE_TIMEOUT: 60
PV_CONNECTION_TIMEOUT: 60

USE_PROGRESS_BAR: false
