# configuration.yml

# configuration for the instrument package
# simple key:value pairs

ADSIM_IOC_PREFIX: "ad:"
GP_IOC_PREFIX: "gp:"

databroker_catalog: training

# default RunEngine metadata
beamline_id: Bluesky_training
instrument_name: Bluesky Case Studies
proposal_id: none
