name: Publish Sphinx Docs to GitHub Pages
on:
  # Build the docs on pushes to main branch, PRs to main branch, and new tags.
  # Publish only on demand.
  push:
    branches:
      - main
    tags:
      - '*'  # all tags
  pull_request:
    branches:
      - main
  workflow_dispatch:   # allow manual triggering
    inputs:
      deploy:
        description: 'Deploy documentation'
        type: boolean
        required: true
        default: false

jobs:

  pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: show timezone
      run: date +%z 

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        # cache: pip

    - name: Install Python requirements
      run: |
        pip install -r ./docs/requirements.txt

    - name: pip list
      run: pip list

    - name: which python
      run: which python

    # # - name: Sphinx
    # #   run: |
    # #     make -C docs html

    # # - name: Publish (push gh-pages branch) only on demand
    # #   uses: peaceiris/actions-gh-pages@v3
    # #   if: ${{ github.event.inputs.deploy }}
    # #   with:
    # #     publish_branch: gh-pages
    # #     github_token: ${{ secrets.GITHUB_TOKEN }}
    # #     publish_dir: docs/build/html
    # #     force_orphan: true
