name: Publish Sphinx docs to GitHub Pages
# see: https://github.com/marketplace/actions/sphinx-to-github-pages

on: [push]
  # push:
  #   branches: [master] # branch to trigger deployment

jobs:

  pages:

    runs-on: ubuntu-20.04

    steps:

    # TODO: install pandoc via apt

    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source
        publish: false
        requirements_path: ./docs/requirements.txt
        cache: true

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
