name: Publish Sphinx Docs to GitHub Pages
on:
  # Build the docs on pushes to main branch, PRs to main branch, and new tags.
  # Publish only on demand.
  push:
    branches:
      - main
    tags:
      - '*'  # all tags
  pull_request:
    branches:
      - main
  workflow_dispatch:   # allow manual triggering
    inputs:
      deploy:
        description: 'Deploy documentation'
        type: boolean
        required: true
        default: false

jobs:

  pages:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:

    # - name: Set timezone
    #   uses: szenius/set-timezone@v1.2
    #   with:
    #     timezoneLinux: "US/Chicago"

    - name: Install pandoc
      run: |
        sudo apt-get -y update && \
        sudo apt-get -y install pandoc

    - name: Build and Commit
      uses: sphinx-notes/pages@v3
      with:
        # cache: true
        # path to conf.py directory
        documentation_path: docs/source
        python_version: 3.9
        requirements_path: ./docs/requirements.txt
        checkout: true

    - name: Publish (push gh-pages branch) only on demand
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event.inputs.deploy }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        force_orphan: true
